name: Build Certbot Loopia Image
on:
  push:
    paths:
      - 'k8s/cert-manager/docker/**'
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: k8s/cert-manager/docker
          push: true
          tags: ghcr.io/${{ github.repository }}/certbot-loopia:latest
