apiVersion: v1
kind: Secret
metadata:
  name: loopia-credentials
  namespace: cert-manager
stringData:
  loopia.ini: |
    dns_loopia_user = LOOPIA_USER_PLACEHOLDER
    dns_loopia_password = LOOPIA_PASS_PLACEHOLDER
