apiVersion: v1
kind: PersistentVolume
metadata:
  name: cert-storage-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/cert-manager
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cert-storage
  namespace: cert-manager
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
